/**
 *
 */
public class HTMLOutputTest {

    // TODO: ADD TEST FOR SEQUENCE OF HTML TAGS
    // TODO: ADD TEST FOR TESTING IF ALL OPENING/CLOSING/SELF-CLOSING TAGS ARE IN THE RIGHT PLACE
    // TODO: ADD TEST IF OUTPUT IS IN THE RIGHT FORMAT
    // TODO: ADD TEST IF OUTPUT DOESN'T CONTAIN ATTRIBUTES, TEXT, COMMENTS, ETC.


}
